name: Rust Build

on:
  pull_request:
    branches:
      - main

jobs:
  # Split up the jobs by OS, as each OS has its
  # own peculiarities for constructing the build environment.

  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      # Boilerplate
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Ubuntu setup
      - name: Apt Setup
        run: sudo apt-get update

      - name: Install dependent libraries
        run: sudo apt-get install -y seccomp

      - name: Ensure the libraries are where we want them
        run: |
          find / -name 'libseccomp*' 2>/dev/null && \
          ld --verbose

      # Common Build
      - name: Build
        run: make


  windows-build:
    runs-on: windows-latest
    steps:
      # Boilerplate
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Common Build
      - name: Build
        run: make

