name: Rust Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [linux-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            ubuntulibraries: "seccomp"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Ubuntu Setup
        if: ${{ matrix.ubuntulibraries }}
        run: |
          sudo apt-get update && \
          sudo apt-get install -y ${{ matrix.ubuntulibraries }}" && \
          find / -name 'libseccomp*' && \
          ld --verbose | grep SEARCH_DIR

      - name: Setup the integration tests
        run: make test-bin

      - name: Run all the tests
        run: cargo test
